#!/usr/bin/env python

import sys
from optparse import OptionParser
import ConfigParser
import csv
import sqlalchemy as sa

###  Parsing class list downloaded from SMU academic information system

# this is a sample, it is changing all the time :-(
sample_smu_class_list_download = '''
ID;ORACLE
;
C;Y1;X1;K"Record Number"
C;Y1;X2;K"Student Name"
C;Y1;X3;K"ID"
C;Y1;X4;K"Reg Status"
C;Y1;X5;K"Program"
C;Y1;X6;K"Major"
C;Y1;X7;K"Credits"
Content-type: text/html; charset=ISO-8859-1
Set-Cookie: SESSID=MEIwMEtOMzEzMDkw;

; Row 2
;
C;Y1
C;X1;K"1"
C;X2;K"Ate, Food"
C;X3;K"A00111111"
C;X4;K"RW - **Web Registered**"
C;X5;K"Bachelor of Arts (4yr)"
C;X6;K"Undeclared"
C;X7;K0
F;W1 1 3
F;W2 2 30
F;W3 3 10
F;W4 4 30
F;W5 5 30
F;W6 6 25
F;W7 7 5
; Row 3
;
C;Y2
C;X1;K"2"
C;X2;K"Baked, Bis K."
C;X3;K"A00222222"
C;X4;K"RW - **Web Registered**"
C;X5;K"Bachelor of Arts (4yr)"
C;X6;K"Undeclared"
C;X7;K0
F;W1 1 3
F;W2 2 30
F;W3 3 10
F;W4 4 30
F;W5 5 30
F;W6 6 25
F;W7 7 5
....
; Row 30
;
C;Y3
C;X1;K"3"
C;X2;K"Yawn, Loud"
C;X3;K"A00333333"
C;X4;K"RW - **Web Registered**"
C;X5;K"Bachelor of Commerce (4yr)"
C;X6;K"Undeclared"
C;X7;K0
F;W1 1 3
F;W2 2 30
F;W3 3 10
F;W4 4 30
F;W5 5 30
F;W6 6 25
F;W7 7 5
</TABLE>
<P class="whitespace1">
E
'''

def smu_extract_class_list(f, sort='by_name'):
    '''
    input: an open file handle to SMU "excel" download file
    analyze the file and extract a class list into a dictionary:
       students[id] = [surname, given_names, program, major]
    return this dictionary
    '''
    students = []
    for x in f.readlines():
        if 'C;X2;' in x:
            surname, given_names = x.split('"')[1].split(',')
            surname = surname.strip()
            given_names = given_names.strip()
            given_names = given_names.strip()
        elif 'C;X3;' in x:
            id = x.split('"')[1]
        elif 'C;X5;' in x:
            program = x.split('"')[1]
            program = program.strip()
        elif 'C;X6;' in x:
            major = x.split('"')[1]
            major = major.strip()
            students.append([id, surname, given_names, '@', program, major])
    return sorted_class_list(students, sort='by_name')


def sorted_class_list(students, sort='by_name'):
    key_func = {}
    key_func['by_name'] = lambda x : x[1]
    key_func['by_id'] = lambda x : x[0]
    return sorted(students, key=key_func[sort])


###  Course database  ---------------------------------------------------------

def mk_sqlite_db(dbpath):
    dburl = 'sqlite:///%s' % dbpath
    db = sa.create_engine(dburl)
    metadata = sa.MetaData(db)

    students = sa.Table('students', metadata,
        sa.Column('id',            sa.String(9),   primary_key=True),
        sa.Column('surname',       sa.String(30)),
        sa.Column('given_names',   sa.String(30)),
        sa.Column('email',         sa.String(30)),
        sa.Column('program',       sa.String(30)),
        sa.Column('major',         sa.String(20)),
    )

    tests = sa.Table('tests', metadata,
        sa.Column('test_id',       sa.String(9),   primary_key=True),
        sa.Column('date',          sa.Date()),
        sa.Column('max_marks',     sa.Integer()),
    )

    results = sa.Table('results', metadata,             
        sa.Column('id',            sa.String(9),   primary_key=True),
        sa.Column('test_id',       sa.String(9),   primary_key=True),
        sa.Column('marks',         sa.Integer()),
    )

    metadata.create_all()

    return metadata


#  insert and update routines  ------------------------------------------------

def populate_students(meta, db_list):
    st = meta.tables['students']
    i = st.insert()
    print st.name
    for x in db_list[2:]:
        print x[:6]
        id, surname, given_names, email, program, major = x[:6]
        print 'insert %s %s' % (id, surname)
        i.execute(id=id, surname=surname, given_names=given_names,
                  email=email, program=program, major=major)


import datetime

def check_students(meta, students, type='curr'):
    '''
    To check if student list matches class list in DB if type='curr'.
    Otherwise check if students can be added safely to class list 
    :Param:
        students = list of student id's to check
        student list is emptied upon exit
        type = 'curr' | 'new'
    :Result:
        list of errors associated with the input if available otherwise
        [] is returned. And a command dict which allows the calling
        program to determine the function to use when forcing error data
        into the db.
        if type='curr':
        Command dict is meaningless.
        Errors:
        students in students param list and not in class list
        students in class list and not in students param list
        students repeated within student param list
        if type='new':
        Errors:
        students in students param list and class list
        students in students param list, not in class list but in db. 
        students repeated within student param list
    '''
    errors = []
    command = {}
    st = meta.tables['students']
    class_list = set([x.id for x in get_class_list(meta)])
    full_list = set([x.id for x in st.select().execute()])
    while students:
        x = students.pop()
        if x in students:
            count = 1
            while x in students:
                students.remove(x)
                count+=1
            errors.append("ID %s repeated %s times"%(x,count))
        command[x] = 'I'
        if x in class_list:
            if type == 'new':
                errors.append("ID %s already in class"%(x))
                command[x] = 'U'
            class_list.remove(x)
        elif type == 'curr':
            errors.append("ID %s not registered in class"%(x))
        elif type == 'new' and x in full_list:
            errors.append("ID %s in DB BUT not registered in class"%(x))
            command[x] = 'U'
    if type == 'cur':
        for x in class_list:
            errors.append("Registered ID %s not found in list"%(x))
    return (errors, command)

def check_results(meta, test, students):
    '''
    To check if students' results can be inserted into db.
    :Param:
        students = list of student id's 
        student list is emptied upon exit
        test = test for which results are to be inserted
    :Result:
        list of errors associated with the input if available otherwise
        [] is returned. And a command dict described bellow.
        Errors:
        students that already have a result for this test
        students that are not in class list
        students that are not mentioned in the list but in class list
        students repeated within student param list
        Command:
        Returns a hash of the student_id as key folowed by either U or I
        as the value indicating that the mark would need updating or
        inserting when a force is issued.
    '''
    command = {}
    errors, xcom = check_students(meta, students[:], type='curr')
    test_list = set([x[0] for x in get_test_results(meta, test)])
    while students:
        x = students.pop()
        while x in students:
            students.remove(x)
        command[x] = 'I'
        if x in test_list:
            command[x] = 'U'
            errors.append("Mark exists for %s, test %s"%(x,test))
    return (errors, command)

def check_test(meta, id):
    '''
    Returns True if test 'id' exists in DB.
    '''
    tt = meta.tables['tests']
    r1 = tt.select(tt.c.test_id == id).execute()
    if r1.fetchall():
        return True
    return False

def insert_results(meta, csv_file, force=False):
    list = read_csv_list(csv_file)
    # Compiling test entry to insert test into tests table
    header = [ 
        ('ID number', 'test_id'), 
        ('Maximum', 'max_marks'),
        ('Date', 'date') 
    ]
    if len(list)<3:
        msg = 'CSV too short, must include three headers describing test'
        raise Exception(msg)
    test = {}
    for i in range(3):
        if i < 3:
            if list[i][0] != header[i][0]:
                msg = 'Error mismatch in header rows %d expecting %s'%(
                    i,header[i][0])
                raise Exception(msg)
            else:
                test[header[i][1]] = list[i][1]
    if '/' in test['date']:
        if len(test['date']) == 8:
            # 31/12/07 format
            test['date'] = datetime.datetime.strptime(test['date'], '%d/%m/%y')
        if len(test['date']) == 10:
            # 31/12/2007 format
            test['date'] = datetime.datetime.strptime(test['date'], '%d/%m/%Y')
        else:
            raise ValueError('unrecognized date format: %s' % test['date'])
    elif '-' in test['date'] and len(test['date']) == 10:
        # 2007-12-07 format
        test['date'] = datetime.datetime.strptime(test['date'], '%Y-%m-%d')
    else:
        raise ValueError('unrecognized date format: %s' % test['date'])
    errors, com = check_results(meta, test['test_id'], [x[0] for x in list[3:]])
    force_test = False
    if check_test(meta, test['test_id']):
        errors.append("Test \"%s\" already in DB"%test['test_id'])
        if force:
            force_test = True 
    if not errors or force:
        if not force:
            print >>sys.stderr, "No errors intercepted. Insert Begin:"
        else:
            print >>sys.stderr, "Insert/Update Begin:"
        if not force_test:
            insert_test(meta, test)
            print >>sys.stderr, "    Test \"%(test_id)s\" inserted"%test
        else:
            update_test(meta, test)
            print >>sys.stderr, "    Test \"%(test_id)s\" updated"%test
        col_map = {'id': 0, 'marks': 1}
        test_id = test['test_id']
        for x in list[3:]:
            in_dict = {'test_id': test_id}
            for k,v in col_map.iteritems():
                in_dict[k]=x[v]
            if com[in_dict['id']] == 'I':
                insert_result(meta, in_dict)
            else:
                update_result(meta, in_dict)
            print >>sys.stderr, "    Student %(id)s marks updated"%in_dict
    else:
        print >>sys.stderr, "The following errors were intercepted:"\
                            "\n    %s"%"\n    ".join(errors)
        
def insert_students(meta, csv_file, force=False):
    header = [ 'id', 'surname', 'given_names', 
               'email', 'program', 'major' ]
    ins_func = insert_student
    col_map = {}
    list = read_csv_list(csv_file)
    for x in header:
        try:
            col_map[x] = list[0].index(x)
        except ValueError:
            raise Exception('Error mismatch in header row')
    if len(header) != len(list[0]):
        raise Exception('Too many columns in csv file')
    errors,com = check_students(meta, 
        [x[col_map['id']] for x in list[1:]], 'new')
    if not errors or force:
        if not force:
            print >>sys.stderr, "No errors intercepted. Insert Begin:"
        else:
            print >>sys.stderr, "Insert/Update Begin:"
        for x in list[1:]:
            in_dict = {}
            for k,v in col_map.iteritems():
                in_dict[k]=x[v]
            if com[in_dict['id']] == 'I':
                insert_student(meta, in_dict)
                print >>sys.stderr, "    Student %(id)s was inserted"%in_dict
            else:
                update_student(meta, in_dict)
                print >>sys.stderr, "    Student %(id)s was updated"%in_dict
    else:
        print >>sys.stderr, "The following errors were intercepted:"\
                            "\n    %s"%"\n    ".join(errors)

def insert_student(meta, student_info):
    '''
    Insert a student/teacher into the db.
    :Param:
    student_info:   A dict containing the following keys and
                    corresponding values.
        'id'            : user_id
        'surname'       : surname (<= 30 chars in length)
        'given_names'   : given names (<= 30 chars in length)
        'email'         : user's email address
        'program'       : user's program (<= 30 chars in length)
                          PROF if the user is a professor.
        'major'         : user's major (<= 30 chars in length)
                          PROF if the user is a professor.
    '''
    return meta.tables['students'].insert().execute(**student_info)

def insert_result(meta, student_info):
    '''
    Insert a student's test result into the db.
    :Param:
    student_info:   A dict containing the following keys and
                    corresponding values.
        'id'            : the students id
        'test_id'       : the id of the test
        'marks'         : the students mark in test 
    '''
    return meta.tables['results'].insert().execute(**student_info)

def insert_test(meta, test_info):
    '''
    Insert a test into the db.
    :Param:
    test_info:   A dict containing the following keys and
                 corresponding values.
        'test_id'   : the test id
        'date'      : the date of the test
        'max_marks' : the maximum mark in test 
    '''
    return meta.tables['tests'].insert().execute(**test_info)

def update_result(meta, student_info):
    '''
    Update a student's test result 
    :Param:
    student_info:   A dict containing the following keys and
                    corresponding values.
        'id'            : the students id
        'test_id'       : the id of the test
        'marks'         : the students mark in test 
    
    '''
    rt = meta.tables['results']
    if not rt.update(sa.sql.and_(
            rt.c.id == student_info['id'],
            rt.c.test_id == student_info['test_id']
            ),values=student_info).execute().rowcount:
        raise Exception(
            'No %(test_id)s Mark for %(id)s to update'%student_info)

def update_test(meta, test_info):
    '''
    Insert a test into the db.
    :Param:
    test_info:   A dict containing the following keys and
                 corresponding values.
        'test_id'   : the test id
        'date'      : the date of the test
        'max_marks' : the maximum mark in test 
    '''
    tt = meta.tables['tests']
    if not tt.update(tt.c.test_id == test_info['test_id'],
           values=test_info).execute().rowcount:
        raise Exception('No test %(test_id)s to update'%test_info)


def update_student(meta, student_info):
    '''
    Update a student/teacher info.
    
    This method will update the student with given id with the
    values in the available parameters.
    
    :Param:
    student_info:   A dict containing the following keys and
                    corresponding values.
        'id'            : user_id of user in db. (required)
        'surname'       : surname (<= 30 chars in length)
        'given_names'   : given names (<= 30 chars in length)
        'email'         : user's email address
        'program'       : user's program (<= 30 chars in length)
                          PROF if the user is a professor.
        'major'         : user's major (<= 30 chars in length)
                          PROF if the user is a professor.
    '''
    st = meta.tables['students']
    if not st.update(st.c.id == student_info['id'],
           values=student_info).execute().rowcount:
        raise Exception('No Student with ID %(id)s'%student_info)

def cancel_students(meta, csv_file="", student_list=[]):
    '''
    Cancel the student with the id's specified in student list or in the
    first column of a csv file. 

    If both supplied csv_file take precedence.
    
    Returns a tuple compsed of (successful_changes, error_msgs)
    '''
    student_info = {
        'program'   : 'CANCELLED',
        'major'     : 'CANCELLED',
    }
    if csv_file:
        student_list = [x[0] for x in read_csv_list(csv_file)]
    err = []
    suc = []
    for x in student_list: 
        student_info['id'] = x
        try:
            update_student(meta, student_info)
            suc.append("%s successfully cancelled"%x)
        except Exception, inst:
            err.append(str(inst))
    return(suc,err)

#  queries  -------------------------------------------------------------------

def meta_auto_load(engine):
    meta = sa.MetaData()
    meta.bind = engine
    meta.reflect()
    return meta


def get_marks(meta, id):
    '''
    return [(test_id, marks, max_marks), ...] for the given student id
    '''
    st = meta.tables['students']
    tt = meta.tables['tests']
    rt = meta.tables['results']
    s = sa.select(
        [tt.c.test_id, rt.c.marks, tt.c.max_marks],
        (id == st.c.id) &
        (st.c.id == rt.c.id) &
        (tt.c.test_id == rt.c.test_id)
        )
    rs = s.execute()
    return list(rs)
 

def get_results(meta, id):
    '''
    return [(test_id, percentage), ...] for the given student id
    sorted by test date
    '''
    st = meta.tables['students']
    tt = meta.tables['tests']
    rt = meta.tables['results']
    s = sa.select(
        [tt.c.test_id, rt.c.marks, tt.c.max_marks],
        (id == st.c.id) &
        (st.c.id == rt.c.id) &
        (tt.c.test_id == rt.c.test_id)
        )
    s = s.order_by(tt.c.date)
    rs = s.execute()
    ys = []
    for x in rs:
        if x.marks != '':
            ys.append((x.test_id, x.marks * 100.0 / x.max_marks))
        else:
            ys.append((x[0], '---'))
    return ys
 
def get_test_results(meta, id):
    '''
    return [(student_id, percentage), ...] for the given test id
    '''
    tt = meta.tables['tests']
    rt = meta.tables['results']
    s = sa.select(
        [rt.c.id, rt.c.marks, tt.c.max_marks],
        (id == tt.c.test_id) &
        (tt.c.test_id == rt.c.test_id)
        )
    rs = s.execute()
    ys = []
    for x in rs:
        if x.marks != '':
            ys.append((x.id, x.marks * 100.0 / x.max_marks))
        else:
            ys.append((x[0], '---'))
    return ys

def get_class_list(meta, include_canceled=False):
    st = meta.tables['students']
    # s = sa.select([st.c.id, st.c.surname, st.c.given_names])
    if include_canceled:
        query = sa.sql.and_(st.c.major != 'PROF')
    else:
        query = sa.sql.and_(st.c.major != 'PROF', st.c.major != 'CANCELLED')
    s = st.select( query )
    s = s.order_by(st.c.surname)
    rs = s.execute()
    return list(rs)


###  printing  ----------------------------------------------------------------

def print_results(meta, include_canceled=False):
    for x in get_class_list(meta, include_canceled):
        name = '%s, %s' % (x.surname, x.given_names)
        print '%s  %-22s' % (x.id, name),
        # print get_marks(meta, x.id)
        ys = get_results(meta, x.id)
        for y in ys:
            try:
                print ' %6.2f%%' % y[1],
            except TypeError:
                print ' %6s ' % y[1],
        print


def print_email(meta, include_canceled=False):
    for x in get_class_list(meta, include_canceled):
        # RFC 822 compliant email address
        print '"%s, %s" <%s>' % (x.surname, x.given_names, x.email)


def print_class_list(meta, include_canceled=False):
    for x in get_class_list(meta, include_canceled):
        name = '%s, %s' % (x.surname, x.given_names)
        print '%s  %-25s %-28s %s, %s' % (x.id, name, x.email, x.program, x.major)
        # print '%s,  %-25s' % (x.id, name)


###  CSV utilities  -----------------------------------------------------------

Header_students = ['id', 'surname', 'given_names', 'email', 'program', 'major']
Header_tests = ['test', 'date', 'maximum']
Header_results = [ 'id', 'test', 'marks']
Header2 = ['Maximum', '', '', '', '', '']
Header3 = ['Date', '', '', '', '', '']


def convert_integer(ls):
    'Replace every integer string in a list with the integer it represents'
    for i,x in enumerate(ls):
        if x.isdigit():
            ls[i] = int(x)
    return ls


def read_csv_list(fname):
    rs = csv.reader(open(fname, 'rb'),
        skipinitialspace = True,
        )
    return map(convert_integer, list(rs))


def print_csv_list(pylist):
    wr = csv.writer(sys.stdout,
        dialect='excel',
        # quoting=csv.QUOTE_NONNUMERIC,
    )
    for x in pylist:
        wr.writerow(x)


def fulldump(meta):
    # this always dumps the whole contents of each table
    # including canceled students
    st = meta.tables['students']
    tt = meta.tables['tests']
    rt = meta.tables['results']
    strows = st.select().execute()
    ttrows = tt.select().execute()
    rtrows = rt.select().execute()
    print '# table STUDENTS'
    print_csv_list([Header_students])
    print_csv_list(strows)
    print
    print '# table TESTS'
    print_csv_list([Header_tests])
    print_csv_list(ttrows)
    print
    print '# table RESULTS'
    print_csv_list([Header_results])
    print_csv_list(rtrows)


def dump_template_for_marker(meta):
    # this never include canceled students
    headers = [
        ('ID number', 'Surname', 'Given name(s)'),
        ('Maximum', '', ''),
        ('Date', '', ''),
    ]
    wr = csv.writer(sys.stdout,
        dialect='excel',
        # quoting=csv.QUOTE_NONNUMERIC,
    )
    for x in headers:
        wr.writerow(x)
    for x in get_class_list(meta):
        wr.writerow(x[:3])
 

def dump_excel_marks(meta, include_canceled=False):
    hdr1 = ['ID number', 'Surname', 'Given name(s)']
    hdr2 = ['Maximum', '', '']
    hdr3 = ['Date', '', '']
    wr = csv.writer(sys.stdout,
        dialect='excel',
        # quoting=csv.QUOTE_NONNUMERIC,
    )
    #@
    print '###  The header lines are incomplete!  ###'
    wr.writerow(hdr1)
    wr.writerow(hdr2)
    wr.writerow(hdr3)
    for x in get_class_list(meta, include_canceled):
        ys = get_marks(meta, x.id)
        ms = [x.id, x.surname, x.given_names]
        for y in ys:
            ms.append(y[1])
        wr.writerow(ms)


###  M a i n  ----------------------------------------------------------------

usage = '''Usage:

    course-util command [options] [files ...]

Available commands:

 create     create sqlite db from downloaded class list
 print      print various plain text tables/lists from the db
 dump       dump various csv lists from the db
 upload     upload test results
 cancel     cancel students from class list

Type "course-util --help command" to get particular details.
'''

commands = [ 'create', 'dump', 'upload', 'print', 'cancel']

helps = {
'create': '''
    course-util create class-list db-file

Create an SQLite DB from the class list downloaded from the
academic information system.
''',

'dump': '''
    course-util dump [option] db-file

Dump various csv list on the standard output.

Exactly one of the following options must be given:

    -f --full      dump the full database table by table
                   (always include canceled students)

    -t --template  excel csv template for the marker
                   (never include canceled students)

    -x --excell    dump a spreadsheet containing all marks
                   in the format what the marker maintains.
    -A --all       include canceled students
''',

'upload' : '''
    course-util update db-file csv-file

Requires a csv file that contains a header row matching
the db-table that will be uploaded to.

Exactly one of the following options must be given:

    -r --results  Upload test results into DB.
    -c --class    Upload student list into DB.

Additionally the following argument can be used:
    -F --force  Forces update of information if
                previously inserted into the DB
''',

'print' : '''
    course-util print [option] db-file

Print various plain text tables/lists from the db.

Exactly one of the following options must be given:

    -r --results    print all results(%) so far.
    -c --class      class list
    -m --email      email list
    -A --all        include canceled students
''',

'cancel': '''
    course-util cancel [option] db-file csv-file | student_id [student_id ...]

Cancel the student with the given student_id in database given by
db-file.
    
    -C --csv    Cancel students listed in the csv-file

The file can be a standard text file with a student ID per line,
optionally it can be a csv file. If a csv file is supplied the first
column will be taken as the student ID to cancel.

If the -C switch is issued the first argument after db-file will be
taken as a path to a csv file.
''',

}


def main():
    opt_parser = OptionParser(usage, add_help_option = False)
    opt_parser.add_option('-h', '--help', 
        action='store_true', dest='help', default=False,
        )

    # dump options
    opt_parser.add_option('-f', '--full', 
        action='store_true', dest='fulldump', default=False,
        )
    opt_parser.add_option('-t', '--template', 
        action='store_true', dest='template', default=False,
        )
    opt_parser.add_option('-x', '--excel', 
        action='store_true', dest='excel', default=False,
        )

    # print options
    opt_parser.add_option('-m', '--email', 
        action='store_true', dest='email', default=False,
        )
    opt_parser.add_option('-c', '--class', 
        action='store_true', dest='classlist', default=False,
        )
    opt_parser.add_option('-r', '--results', 
        action='store_true', dest='results', default=False,
        )

    # whether to include canceled students into prints or some dumps
    opt_parser.add_option('-A', '--all', 
        action='store_true', dest='include_cancelled', default=False,
        )

    # upload options
    opt_parser.add_option('-F', '--force', 
        action='store_true', dest='force_flag', default=False,
        )

    # cancel
    opt_parser.add_option('-C', '--csv', 
        action='store_true', dest='csv_flag', default=False,
        )

    (options, args) = opt_parser.parse_args()

#    import logging
#
#    logging.basicConfig()
#    logging.getLogger('sqlalchemy.engine').setLevel(logging.INFO)

    if len(args) < 1 or (args[0] not in commands):
        print usage
        raise SystemExit(0)
    else:
        cmd = args[0]

    opt_parser.usage = helps[cmd]
    if options.help:
        print helps[cmd]
        raise SystemExit(0)

    if cmd == 'create':
        if len(args) != 3:
            opt_parser.error('incorrect number of arguments')
        students = smu_extract_class_list(open(args[1]))
        meta = mk_sqlite_db(args[2])
        populate_students(meta, students)

    elif cmd == 'dump':
        if len(args) != 2:
            opt_parser.error('incorrect number of arguments')
        engine = sa.create_engine('sqlite:///%s' % args[1])
        meta = meta_auto_load(engine)
        if options.email or options.classlist or options.results:
            opt_parser.error('invalid option')
        elif options.template:
            dump_template_for_marker(meta)
        elif options.fulldump:
            fulldump(meta)
        elif options.excel:
            dump_excel_marks(meta, options.include_cancelled)
        else:
            opt_parser.error('missing option')

    elif cmd == 'print':
        if len(args) != 2:
            opt_parser.error('incorrect number of arguments')
        engine = sa.create_engine('sqlite:///%s' % args[1])
        meta = meta_auto_load(engine)
        if options.template or options.fulldump:
            opt_parser.error('invalid option')
        elif options.email:
            print_email(meta, options.include_cancelled)
        elif options.classlist:
            print_class_list(meta, options.include_cancelled)
        elif options.results:
            print_results(meta, options.include_cancelled)
        else:
            opt_parser.error('missing option')

    elif cmd == 'upload':
        if len(args) != 3:
            opt_parser.error('incorrect number of arguments')
        engine = sa.create_engine('sqlite:///%s' % args[1],
            strategy='threadlocal')
        meta = meta_auto_load(engine)
        csv_file = args[2]
        force_flag = False 
        if options.force_flag:
            force_flag = True
        if options.classlist:
            insert_students(meta, csv_file, force_flag) 
        elif options.results:
            insert_results(meta, csv_file, force_flag) 
        else:
            opt_parser.error('missing or invalid option')

    elif cmd == 'cancel':
        if len(args) < 3:
            opt_parser.error('incorrect number of arguments')
        engine = sa.create_engine('sqlite:///%s' % args[1],
            strategy='threadlocal')
        meta = meta_auto_load(engine)
        if options.csv_flag:
            success_msgs, error_msgs = \
                cancel_students(meta, csv_file = args[2])
        else:
            success_msgs, error_msgs = \
                cancel_students(meta, student_list = args[2:])
        if success_msgs:
            print >>sys.stderr, "The following changes were done:"
            print >>sys.stderr, "  %s"%"\n  ".join(success_msgs)
        if error_msgs:
            print >>sys.stderr, "The following errors have occurred:"
            print >>sys.stderr, "  %s"%"\n  ".join(error_msgs)

###
main()

# vim: ai ts=4 et sw=4
